version: '3.1'

services:
    mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - ./mongo/restore.sh:/docker-entrypoint-initdb.d/restore.sh
            - ./mongo/backup/:/backup
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    mongo-tests:
        container_name: mongo-tests
        image: mongo:latest
        ports:
            - 37017:27017
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        ports:
            - 8081:8081
        restart: unless-stopped
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USERNAME}
            ME_CONFIG_BASICAUTH_PASSWORD : ${EXPRESS_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongo:27017/

    mssql:
        container_name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 1433:1433
        volumes:
            - ./mssql/backup.sql:/backup.sql
            - ./mssql/entrypoint.sh:/entrypoint.sh
        restart: unless-stopped
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
        entrypoint: [/entrypoint.sh]

    mssql-tests:
        container_name: mssql-tests
        image: mcr.microsoft.com/mssql/server:2022-latest
        ports:
            - 2433:1433
        restart: unless-stopped
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}

    api:
        container_name: film-forum-api
        build: api/
        ports:
            - 80:80
        restart: unless-stopped
        environment:
            MONGODB_USERNAME: ${MONGODB_USERNAME}
            MONGODB_PASSWORD: ${MONGODB_PASSWORD}
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
