version: '3.1'

services:
    mongodb:
        container_name: mongo
        image: mongo:latest
        restart: unless-stopped
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

    mongo-express:
        container_name: mongo-express
        image: mongo-express:latest
        ports:
            - 8081:8081
        restart: unless-stopped
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
            ME_CONFIG_BASICAUTH_USERNAME: admin
            ME_CONFIG_BASICAUTH_PASSWORD : ${EXPRESS_PASSWORD}
            ME_CONFIG_MONGODB_URL: mongodb://root:${MONGODB_PASSWORD}@mongo:27017/
